### ISSUE TITLE
Enhancement - Unresolved Reference 

### ISSUE THREAD

**Issue by NGimhana** [ballerina-attic/plugin-intellij#823]
**Description:**
Unresolved Reference for common packages like HTTP, io in IntelliJ IDEA Editor. But the code compiles and running smoothly. Need some Indication enhancement of the style of the code base.

**Affected Versions:**
Ballerina 0.976.1-SNAPSHOT

**OS, DB, other environment details and versions:**
UBUNTU 16.04 x64

**Comment by this** [comment]
This repository is retired. Please create this issue in the new location https://github.com/ballerina-platform/ballerina-lang/tree/master/tool-plugins/intellij

**Comment by NGimhana** [comment]
Didn't aware on that.Thanks. I'll re-open this there.
