### ISSUE TITLE
When debugging Ballerina Module using Intellij plugin, debugger never connects to runtime

### ISSUE THREAD

**Issue by wyldbill** [ballerina-attic/plugin-intellij#825]
Ballerina version: 0.991.0 (current)
Ballerina plugin version: 0.991.1 (current)
Intellij Version: 2019.1.3 (Ultimate)
OS: Windows 10

Every time Ballerina program is launched as debug, program runs on a different debug port. Debug window shows the debugger waiting to connect. Program runs and creates output, debugger never connects, programs never stops at breakpoints.

Note that this only occurs when the Main file is in a Module. If the Main is in the default(root) namespace, the debugger connects as expected.

**Comment by nadeeshaan** [comment]
@wyldbill can you create the issue at https://github.com/ballerina-platform/ballerina-lang under the following label? **_Component/IntellijPlugin_**

**Comment by wyldbill** [comment]
Done. Apologies for waking the dead :)
